// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJmKr-bfjH-7hE_amy-iidDX2Vmd49_pY',
    appId: '1:979725807479:web:8f9c28ea527e91b9c0bb72',
    messagingSenderId: '979725807479',
    projectId: 'flash-chat-76154',
    authDomain: 'flash-chat-76154.firebaseapp.com',
    storageBucket: 'flash-chat-76154.appspot.com',
    measurementId: 'G-HSDT65KSND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq377PdY-QrF8qR64xzXTkppNEGCRWAds',
    appId: '1:979725807479:android:73b9b959825d5406c0bb72',
    messagingSenderId: '979725807479',
    projectId: 'flash-chat-76154',
    storageBucket: 'flash-chat-76154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5rMGr6GqQKdc_1jj0jNGI4q3KZy3KrA',
    appId: '1:979725807479:ios:32ed88485d1eec10c0bb72',
    messagingSenderId: '979725807479',
    projectId: 'flash-chat-76154',
    storageBucket: 'flash-chat-76154.appspot.com',
    iosClientId: '979725807479-mota84pl84876lkb7rsh1r5hhs0d5r78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU5rMGr6GqQKdc_1jj0jNGI4q3KZy3KrA',
    appId: '1:979725807479:ios:32ed88485d1eec10c0bb72',
    messagingSenderId: '979725807479',
    projectId: 'flash-chat-76154',
    storageBucket: 'flash-chat-76154.appspot.com',
    iosClientId: '979725807479-mota84pl84876lkb7rsh1r5hhs0d5r78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
